name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: python --version
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python --version
    - run: sh Scripts/ci.sh
      id: script
    - name: Commit
      uses: EndBug/add-and-commit@v7
      with:
        add: 'Package.swift Sources'
        message: "add ${{ steps.script.outputs.tag }}"
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.script.outputs.tag }}"
        files: 'Open3D/*.xcframework.zip'
        prerelease: false
